import Nav, { NavLink } from '@components/Nav';
import Spacer from '@components/Spacer';
import { useColorMode } from '@hooks/UseColorMode';
import Hero from 'module/home/Hero';
import Head from 'next/head';

export default function Home() {
  const { htmlLyout, colorMode } = useColorMode();

  const menu: NavLink[] = [
    {
      label: 'About',
      link: '/about',
    },
    {
      label: 'My Journey',
      link: '/my-journey',
    },
    {
      label: 'Works',
      link: '/works',
    },
    {
      label: 'Contact',
      link: '/contact',
    },
  ];

  return (
    <div data-theme={colorMode} className="h-screen w-screen">
      {/* page head */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* items */}
      <Nav menu={menu} customContent={htmlLyout} />
      <Spacer />
      <div className="px-8 lg:px-60">
        <Hero />
      </div>
    </div>
  );
}
