import Button from '@components/Button';
import { useColorMode } from '@hooks/UseColorMode';
import Head from 'next/head';

export default function Home() {
  const { htmlLyout, colorMode } = useColorMode();
  return (
    <div data-theme={colorMode} className="h-screen w-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button label="Home" />
      {htmlLyout}
    </div>
  );
}
