import Head from 'next/head';
import { Flex } from '@chakra-ui/react';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex height="100vh" alignItems="center" justifyContent="center">
        <p>
          this is my final version of protfoilo with notion api or mdx or ghost
          cms
        </p>
      </Flex>
    </div>
  );
}
