import Head from 'next/head';

const SEOHead = () => (
  <Head>
    <title>Rajeev Rajchal</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

export default SEOHead;
